"""add job type and format fields

Revision ID: 29a4f9c2ca8c
Revises: 81a8034fa5f0
Create Date: 2026-06-19 20:09:20.258873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a4f9c2ca8c'
down_revision: Union[str, Sequence[str], None] = '81a8034fa5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.Enum('VIDEO', 'AUDIO', 'IMAGE', 'DOCUMENT', name='jobtype'), nullable=False))
    op.add_column('jobs', sa.Column('input_format', sa.String(length=16), nullable=False))
    op.add_column('jobs', sa.Column('output_format', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'output_format')
    op.drop_column('jobs', 'input_format')
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###
